### PR TITLE
Remote forwarding

### PR DESCRIPTION
**Pull request by progrium**

### CODE REVIEW

**Comment by progrium** [comment]
@eliastor there's some conflicts with master

**Comment by eliastor** [comment]
I can't understand why these conflicts appears. Incoming changes should be accepted. What should I do?

**Comment by progrium** [comment]
Try the Resolve Conflicts button here if you see it

**Comment by eliastor** [comment]
I have no write access)

**Comment by eliastor** [comment]
you can accept all changes from remote-forwarding by yourself or tell me what to do from my side

**Comment by progrium** [comment]
you can accept the invite and resolve the conflicts :)

**Pull request merged**
