### PR TITLE
Update golang.org/x/crypto/ssh

### PR DESCRIPTION
**Pull request by gustavosbarreto**
Update golang.org/x/crypto to fix issues related to RSA SHA-2 signatures.

Related to:

* #165 
* #176

### CODE REVIEW

**Comment by belak** [comment]
It looks like this is going to require a bump to Go 1.13 for the minimum supported version in Circle CI (because 1.13 added crypto/ed25519) before this can get merged. If you don't have the time to get to it soon, I'd be happy to.

**Comment by gustavosbarreto** [comment]
> It looks like this is going to require a bump to Go 1.13 for the minimum supported version in Circle CI (because 1.13 added crypto/ed25519) before this can get merged. If you don't have the time to get to it soon, I'd be happy to.

@belak I would be grateful for any help.

**Comment by belak** [comment]
That was easier to change than I expected! Thanks for doing this!

**Comment by belak** [comment]
Alright, it's been bumped and a new version tagged.

**Pull request merged**
